name: Greeting on variable day

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "$TEST"
        env:
          TEST: ${{ vars.TEST }}
