name: Test Building
  
on:
  workflow_dispatch:

jobs:
   
  build:
    runs-on: windows-latest
    
    steps:
      - name: Execute under powershell 
        shell: powershell
        run: $PSVersionTable

      - name: Execute under pwsh
        shell: pwsh
        run: $PSVersionTable
        
