name: Greeting on variable day

on:
  workflow_dispatch:
    inputs:
      prod_or_dev:
        description: 'prod or dev'
        required: false
        default: 'dev'
        
jobs:

  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.prod_or_dev }}
    steps:
      - run: echo "$TEST"
        env:
          TEST: ${{ vars.TEST }}
