name: Build

on: 
  workflow_dispatch:
    inputs:
      scheduled_simulate:
        type: boolean
        description: 'Simulate scheduled run'
        
  #schedule:
    #- cron: 0/5 * * * *
    
jobs:

  build:
    permissions:
      contents: write   # Required to upload tag the release
    runs-on: windows-latest
    steps:
        - run: Write-Host 'Running build'
        - name: Setup version
          id: version
          env:
            githubRunNumber: ${{ github.run_number }}
          run: |
            $version = [System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::Now, "E. Australia Standard Time").ToString("yyyy.MM.dd.") + $env:githubRunNumber
            "value=$version" >> $env:GITHUB_OUTPUT

        - uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.version.outputs.value }}
            body: '&nbsp;'
