name: Build

on: 
  workflow_dispatch:
    inputs:
      scheduled_simulate:
        type: boolean
        description: 'Simulate scheduled run'
        
  #schedule:
    #- cron: 0/5 * * * *
    
jobs:
  build-required:
    runs-on: windows-latest
    outputs:
      required: ${{ steps.build-check.outputs.required }}    
    steps:
        - uses: actions/checkout@v4
          #with:
            #fetch-depth: 0 
    
        - name: CHECK Whether build should run
          id: build-check
          env:
            schedule: ${{ github.event.schedule || (inputs.scheduled_simulate && '* * * * *') }}
          run: |
            Write-Host "Running build with schedule: $($env:schedule)"
            git describe --exact-match --tags HEAD
            $hasCommitsSinceLastTag = $LASTEXITCODE -ne 0
            Write-Host "hasCommitsSinceLastTag = $hasCommitsSinceLastTag"
            $required = if ($env:schedule -ne '') { $commitsSinceLastTag } else { $true }
            "required=$required" >> $env:GITHUB_OUTPUT

  build:
    needs: build-required
    if: ${{ needs.build-required.outputs.required == 'true' }}
    runs-on: windows-latest
    steps:
        - run: Write-Host 'Running build'
